version: '3.7'
services:
  dealership-app:
    restart: always
    build: 
      context: ./dealership-app/ClientApp/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - node-server
    tty: true
  node-server:
    restart: always
    build: 
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017
    volumes:
      - './mongodb:/data/db'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example